name: "Deploy all given apps on the given stage"
description: "does what it says in the name"

inputs:
  stage:
    description: The stage on which the apps shall be deployed
    required: true

  apps:
    description: list of apps
    required: true

runs:
  using: composite
  steps:
    - name: Create releases
      run: |
        declare -A stages
        for stage in $(echo '${{ inputs.apps }}' | jq '.[]'); do
          echo "Creating Release:"
          echo $stage
          stages[stage]="release_id_from_setops"
        done
        echo $stages
      shell: bash
