name: "Deploy all given apps on the given stage"
description: "does what it says in the name"

inputs:
  stage:
    description: The stage on which the apps shall be deployed
    required: true

  apps:
    description: list of apps
    required: true

runs:
  using: composite
  steps:
    - name: Create releases
      run: |
        declare -a stages
        for stages in $(echo '${{ inputs.apps }}' | jq '.[]'); do
          stages+=stage
        done

        declare -A stages_with_release_id

        # RANDOM should be replaced with calls to setops
        echo "Generating Releases"
        for stage in ${stages[@]}; do
          stages_with_release_id[$stage]=$RANDOM
        done

        echo "Run pre-deploy-commands"

        echo "Commit"

        echo "Activating Releases"
        for stage in "${stages[@]}"; do
          release_id=${stages_with_release_id[$stage]}
          echo Activating Release: $stage -- $release_id
        done

        echo "Commit"
      shell: bash
