name: "Build image and push it with a myriad of tags"
description: "does what it says in the name"

inputs:
  stages:
    description: List of stages in JSON format, e.g. '["production" ,"demo"]'
    required: true
  apps:
    description: List of apps in JSON format, e.g. '["web", "clock", "worker"]'
    required: true
  setops_host:
    description: The setops host
    required: false
    default: api.setops.co

runs:
  using: composite
  steps:
    - name: Detect setops user
      id: detect_setops_user
      run: |
        if [ -n "${{ secrets.SETOPS_USER}}" ]
          setops_user=${{ secrets.SETOPS_USER }}
        fi
        echo $setops_user
      shell: bash
    - name: Build Image Names
      id: build_image_names
      run: |
        declare -a images
        for stage in $(echo '${{ inputs.stages }}' | jq -r '.[]'); do
          for app in $(echo '${{ inputs.apps }}' | jq -r '.[]'); do
            images+=("${{ inputs.setops_host }}/zweitag/my_project/$stage/$app:latest")
          done
        done

        # https://stackoverflow.com/a/2317171
        concatenated_images=$(printf ",%s" "${images[@]}")
        concatenated_images=${concatenated_images:1}

        echo "::set-output name=concatenated_images::$concatenated_images"
      shell: bash
    - name: output_images
      run: |
        echo ${{ steps.build_image_names.outputs.concatenated_images }}
      shell: bash
