name: "Build image and push it with a myriad of tags"
description: "does what it says in the name"

inputs:
  stages:
    description: list of stages
    required: true
  apps:
    description: list of apps
    required: true

runs:
  using: composite
  steps:
    - name: Build Image Names
      id: build_image_names
      run: |
        declare -a images
        for stage in $(echo '${{ inputs.stages }}' | jq -r '.[]'); do
          for app in $(echo '${{ inputs.apps }}' | jq -r '.[]'); do
            images+=("api.setops.co/zweitag/my_project/$stage/$app:latest")
          done
        done

        # https://stackoverflow.com/a/2317171
        concatenated_images=$(printf ",%s" "${images[@]}")
        concatenated_images=${concatenated_images:1}

        echo $concatenated_images


        IMAGES_AS_CSV_STRING=` \
        echo '{"stages": ${{ inputs.stages }}, "apps": ${{ inputs.apps }} }' \
        | jq '[.stages[] as $stages | .apps[] as $apps | {stage: $stages, app: $apps}]' \
        | jq -c 'map("api.setops.co/zweitag/my_project/" + .["stage"] + "/" + .["app"] + ":latest")' \
        | sed 's/\[//g' \
        | sed 's/\]//g' \
        `
        echo $IMAGES_AS_CSV_STRING
        echo "::set-output name=images_as_csv_string::$IMAGES_AS_CSV_STRING"
      shell: bash
    - name: output_images
      run: |
        echo ${{ steps.build_image_names.outputs.images_as_csv_string }}
      shell: bash
