name: "Build image and push it with a myriad of tags"
description: "does what it says in the name"

inputs:
  stages:
    description: list of stages
    required: true
  apps:
    description: list of apps
    required: true

runs:
  using: composite
  steps:
    - name: foo
      run: |
        echo '{"stages": ${{ inputs.stages }}, "apps": ${{ inputs.apps }} }' \
        | jq '.stages[] as $stages | .apps[] as $apps | [$stages, $apps]' \ 
        | jq -c 'map("api.setops.co/zweitag/veritrustid/" + .[0] + "/" + .[1] + ":latest")'
      shell: bash
