name: "Build image and push it with a myriad of tags"
description: "does what it says in the name"

inputs:
  stages:
    description: list of stages
    required: true
  apps:
    description: list of apps
    required: true

runs:
  using: composite
  steps:
    - name: build_image_names
      run: |
        IMAGES_AS_CSV_STRING=` \
        echo '{"stages": ${{ inputs.stages }}, "apps": ${{ inputs.apps }} }' \
        | jq '[.stages[] as $stages | .apps[] as $apps | {stage: $stages, app: $apps}]' \
        | jq -c 'map("api.setops.co/zweitag/my_project/" + .["stage"] + "/" + .["app"] + ":latest")' \
        | sed 's/\[//g' \
        | sed 's/\]//g' \
        `
        echo $IMAGES_AS_CSV_STRING
        echo "::set-output name=images_as_csv_string::$IMAGES_AS_CSV_STRING"
      shell: bash
    - name: output_images
      run: |
        echo ${{ steps.build_image_names.outputs.images_as_csv_string }}
      shell: bash
