name: "Build image and push it with a myriad of tags"
description: "does what it says in the name"

inputs:
  stages:
    description: list of stages
    required: true

runs:
  using: composite
  steps:
    - name: foo
      run: |
        echo "${{ inputs.stages }}"
      shell: bash
