name: Matrix
on: push

jobs:
  matrix_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        envs: [1, 2]
    steps:
      - name: Sleep for 15 seconds
        run: sleep 15s
        shell: bash
