name: Deployment
on: push

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest

    steps:
      - name: "Build image and push it to setops image registry"
        id: build_and_push_app
        uses: ./.github/actions/build_and_push_image
