name: Deployment
on: push

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Build image and push it to setops image registry"
        id: build_and_push_app
        uses: ./.github/actions/build_and_push_image
        with:
          stages: '["production", "demo"]'
          apps: '["web", "clock", "worker"]'

  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stage: ${{ fromJson('["production", "demo"]') }}
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Deploy stage"
        id: deployment
        uses: ./.github/actions/deploy
        with:
          apps: '["web", "clock", "worker"]'
